[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
neuro_ledger = "BtyM5xCXDSAUupX2niKU5jQ46xtcnLDbU99KrpDEZ625"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
